"""initial migration

Revision ID: 0b3ded920d9f
Revises: 
Create Date: 2022-11-22 09:21:23.078791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b3ded920d9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_sys_id', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_sys_id')
    )
    op.create_table('Action',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('action_sys_id', sa.String(length=25), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('action_date', sa.Date(), nullable=False),
    sa.Column('by', sa.String(length=25), nullable=True),
    sa.ForeignKeyConstraint(['by'], ['User.user_sys_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('action_sys_id')
    )
    op.create_table('Item',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_sys_id', sa.String(length=25), nullable=False),
    sa.Column('action_id', sa.String(length=25), nullable=True),
    sa.Column('item', sa.String(length=255), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('buying_price', sa.Float(), nullable=False),
    sa.Column('selling_price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['Action.action_sys_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item'),
    sa.UniqueConstraint('item_sys_id')
    )
    op.create_table('Sale_Two',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.String(length=25), nullable=True),
    sa.Column('item_id', sa.String(length=25), nullable=True),
    sa.Column('buying_price', sa.Float(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['Item.item_sys_id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['Action.action_sys_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sale_Two')
    op.drop_table('Item')
    op.drop_table('Action')
    op.drop_table('User')
    # ### end Alembic commands ###
