"""creating the sales table

Revision ID: 8c00b4cb3c2b
Revises: d7f48bca1eb3
Create Date: 2022-05-17 16:08:37.028278

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c00b4cb3c2b'
down_revision = 'd7f48bca1eb3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Sale',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sale_id', sa.String(length=25), nullable=True),
    sa.Column('item_id', sa.String(length=25), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('units', sa.Numeric(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['Item.item_sys_id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['Action.action_sys_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Sale')
    # ### end Alembic commands ###
